### ISSUE TITLE
Scroll wheel on mice does not scroll through hotbar

### ISSUE THREAD

**Issue by RubikOwl** [PojavLauncherTeam/PojavLauncher_iOS#390]
### Describe the bug

Unless I’m doing something wrong, it appears that using a scroll wheel on a mouse does not scroll through the hotbar. I am able to scroll with the trackpad on my ipad’s case.

### Steps To Reproduce

```markdown
Basically just use the launcher as normal, no weird steps.
```

### Expected Behavior

Being able to scroll with a mouse.

### Platform

```markdown
- Device model: iPad Air 4th gen
- iOS version: ios 16
- PojavLauncher version: Most recent version as of 9/30/2022 at 9:00 mountain time
```

### Anything else?

Really love this app, so cool that you got java edition to work on ios and android!

**Comment by khanhduytran0** [comment]
Please let us know the Minecraft version, as it’s working for me in 1.19.2.
Make sure touchscreen mode is turned off(?)

**Comment by Figurant16** [comment]
I'm on iPad Pro with iOS 16.1 beta and have the same issue (on every version). Touchpad mode is turned off.
Maybe that's and issue with ipados beta ?

**Comment by InfernoNova9999** [comment]
You have to install debugify mod. That fixes it 

if that didnt work go to your hardware keyboard setting where you can map the caps lock key to command key etc and choose the second keyboard.

**Comment by InfernoNova9999** [comment]
If i'm not using the mod the scroll wheel still doesnt work. I cant play 1.8.9 or any vanilla version with scroll wheel. @khanhduytran0

**Comment by InfernoNova9999** [comment]
It should work now.

**Comment by ShonP40** [comment]
Nope, still have this issue.
Also, I’ve noticed that the scroll wheel does work if I connect my iPad to an external monitor, but when its on the iPad’s display, the scroll wheel doesn’t work.

**Comment by alcziyad** [comment]
J

**Comment by Zhou-Shilin** [comment]
the scroll wheel works for me in 1.8.9, but in higher versions such as 1.18.2, sometimes time it takes me 3~4 times scrolling for *one* slot :(

**Comment by ItAnthon** [comment]
Today, I finally tested a Bluetooth mouse.

This mouse worked as intended, (although it was laggy cause of Bluetooth of course) even the side buttons worked, which I didn’t expect. If you haven’t already, please use the latest github actions build.

If curious: iPadOS 16.6.1, TrollStore, Latest PojavLauncher GitHub actions build. (Close this)

**Comment by ItAnthon** [comment]
@Zhou-Shilin Turn on “Discrete Scrolling” in mouse settings in newer versions.
